name: Build Project
on:
  workflow_call:
    outputs:
      pluginName:
        description: Project name detected by parsing build spec file
        value: ${{ jobs.check-event.outputs.pluginName }}
jobs:
  check-event:
    name: Check GitHub Event Data 🔎
    runs-on: windows-2022
    defaults:
      run:
        shell: pwsh
    outputs:
      package: ${{ steps.setup.outputs.package }}
      config: ${{ steps.setup.outputs.config }}
      commitHash: ${{ steps.setup.outputs.commitHash }}
      pluginName: ${{ steps.setup.outputs.pluginName }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check Event Data ☑️
        id: setup
        run: |
          # Check Event Data ☑️
          $EventName = $env:GITHUB_EVENT_NAME
          $RefName = $env:GITHUB_REF_NAME
          $CommitHash = $env:GITHUB_SHA.Substring(0, 9)

          switch ($EventName) {
            "pull_request" {
              "package=false" >> $env:GITHUB_OUTPUT
              "config=RelWithDebInfo" >> $env:GITHUB_OUTPUT
            }
            "push" {
              "package=true" >> $env:GITHUB_OUTPUT
              if ($RefName -match '^[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta).+)?$') {
                "config=Release" >> $env:GITHUB_OUTPUT
              } else {
                "config=RelWithDebInfo" >> $env:GITHUB_OUTPUT
              }
            }
            "workflow_dispatch" {
              "package=false" >> $env:GITHUB_OUTPUT
              "config=RelWithDebInfo" >> $env:GITHUB_OUTPUT
            }
            default {
              "package=false" >> $env:GITHUB_OUTPUT
              "config=RelWithDebInfo" >> $env:GITHUB_OUTPUT
            }
          }
          "commitHash=${CommitHash}" >> $env:GITHUB_OUTPUT

          $BuildSpec = Get-Content -Path buildspec.json -Raw | ConvertFrom-Json
          $PluginName = $BuildSpec.displayName
          if (-not $PluginName) {
            $PluginName = $BuildSpec.name
          }
          "pluginName=${PluginName}" >> $env:GITHUB_OUTPUT

  windows-build:
    name: Build for Windows 🪟
    runs-on: windows-2022
    needs: check-event
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set Up Environment 🔧
        id: setup
        run: |
          # Set Up Environment 🔧
          if ( $Env:RUNNER_DEBUG -ne $null ) {
            Set-PSDebug -Trace 1
          }

          $BuildSpec = Get-Content -Path buildspec.json -Raw | ConvertFrom-Json
          $ProductName = $BuildSpec.name
          $ProductVersion = $BuildSpec.version

          "pluginName=${ProductName}" >> $env:GITHUB_OUTPUT
          "pluginVersion=${ProductVersion}" >> $env:GITHUB_OUTPUT

      - name: Build Plugin 🧱
        uses: ./.github/actions/build-plugin
        with:
          target: x64
          config: ${{ needs.check-event.outputs.config }}

      - name: Package Plugin 📀
        uses: ./.github/actions/package-plugin
        with:
          target: x64
          config: ${{ needs.check-event.outputs.config }}
          package: ${{ fromJSON(needs.check-event.outputs.package) }}

      - name: Upload Artifacts 📡
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-windows-x64-${{ needs.check-event.outputs.commitHash }}
          path: ${{ github.workspace }}/release/${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-windows-x64*.*
